[toolchain]
package_manager = "npm"

[features]
resolution = true
skip-lint = false

[programs.localnet]
lock_vault = "41TexnrHDMV4ASJmqNNFcgQ7RBk6N193yvukfiCzKQmD"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test -p lock-vault"
